Repository Odontolog/odontolog, pull requests merged in 2025-10, with the labels that each got.

#32 PDS-145 feat(backend): Adicionando endpoint de submit for review para Planos de Tratamento
  bruno/Treatment Plan/Submit Treatment Plan for Review.bru
  server/src/main/java/br/ufal/ic/odontolog/api/TreatmentPlanApi.java
  server/src/main/java/br/ufal/ic/odontolog/config/GlobalControllerExceptionHandler.java
  server/src/main/java/br/ufal/ic/odontolog/controllers/TreatmentPlanController.java
  server/src/main/java/br/ufal/ic/odontolog/dtos/TreatmentPlanSubmitForReviewDTO.java
  server/src/main/java/br/ufal/ic/odontolog/exceptions/ReviewSubmissionException.java
  server/src/main/java/br/ufal/ic/odontolog/services/TreatmentPlanService.java
  server/src/main/java/br/ufal/ic/odontolog/states/treatmentPlan/TreatmentPlanState.java
  server/src/main/java/br/ufal/ic/odontolog/states/treatmentPlan/TreatmentPlanStates.java
  server/src/test/java/br/ufal/ic/odontolog/services/TreatmentPlanServiceUnitTest.java
Labels: backend

#38 PDS-148 feat(backend): Adicionando endpoint GET para buscar o histórico de atividade de um reviewable
  bruno/Reviewables/Get Reviewable History.bru
  bruno/collection.bru
  server/src/main/java/br/ufal/ic/odontolog/api/ReviewableApi.java
  server/src/main/java/br/ufal/ic/odontolog/controllers/ReviewableController.java
  server/src/main/java/br/ufal/ic/odontolog/mappers/ActivityMapper.java
  server/src/main/java/br/ufal/ic/odontolog/services/ReviewableService.java
  server/src/main/java/br/ufal/ic/odontolog/services/TreatmentPlanService.java
  server/src/test/java/br/ufal/ic/odontolog/services/ReviewableServiceUnitTest.java
  server/src/test/java/br/ufal/ic/odontolog/services/TreatmentPlanServiceUnitTest.java
Labels: backend

#42 feat: Criado o componente modal de validação
  frontend/src/features/treatment-plan/header.tsx
  frontend/src/features/treatment-plan/requests.ts
  frontend/src/features/treatment-plan/review-modal.tsx
Labels: frontend

#37 feat(integration): Integração do endpoint submit for review com o modal
  frontend/src/features/patient/procedures/models.ts
  frontend/src/features/treatment-plan/request-review-modal.tsx
  frontend/src/features/treatment-plan/requests.ts
  server/src/main/java/br/ufal/ic/odontolog/controllers/TreatmentPlanController.java
Labels: integration

#34 pds-146 feat(backend): Adicionado endpoint da listagem de pacientes
  server/src/main/java/br/ufal/ic/odontolog/controllers/PatientController.java
  server/src/main/java/br/ufal/ic/odontolog/dtos/PatientDTO.java
  server/src/main/java/br/ufal/ic/odontolog/mappers/PatientMapper.java
  server/src/main/java/br/ufal/ic/odontolog/services/PatientService.java
  server/src/test/java/br/ufal/ic/odontolog/services/PatientServiceUnitTest.java
Labels: backend
